// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTBTbntuKa3ifA5AK5n44pyYPxwGjiHM',
    appId: '1:175024168085:web:5e6f9a95ea34649febcf9c',
    messagingSenderId: '175024168085',
    projectId: 'audifinal',
    authDomain: 'audifinal.firebaseapp.com',
    storageBucket: 'audifinal.firebasestorage.app',
    measurementId: 'G-L7HFDRY4C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPMqO3kSEVYynFtulJ54phIR6vjZc9ojg',
    appId: '1:175024168085:android:eee36f09edd4a101ebcf9c',
    messagingSenderId: '175024168085',
    projectId: 'audifinal',
    storageBucket: 'audifinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWCoDxornhh5nKmdsRHRHyv8f1r59p4I',
    appId: '1:175024168085:ios:91aa461eea176d73ebcf9c',
    messagingSenderId: '175024168085',
    projectId: 'audifinal',
    storageBucket: 'audifinal.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYWCoDxornhh5nKmdsRHRHyv8f1r59p4I',
    appId: '1:175024168085:ios:91aa461eea176d73ebcf9c',
    messagingSenderId: '175024168085',
    projectId: 'audifinal',
    storageBucket: 'audifinal.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTTBTbntuKa3ifA5AK5n44pyYPxwGjiHM',
    appId: '1:175024168085:web:7c4d1197a214897debcf9c',
    messagingSenderId: '175024168085',
    projectId: 'audifinal',
    authDomain: 'audifinal.firebaseapp.com',
    storageBucket: 'audifinal.firebasestorage.app',
    measurementId: 'G-SQ01YC97D2',
  );
}
